### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [Fr0stFree/CinemaUGC#9]
Ловко вы решили сделать сразу для нескольких брокеров 👍 
На всякий случай уточню, что с предполагаемым потоком данных redis и rabbitmq не справятся, можем расчитывать на сотни миллионов в сутки. Эта работа только для Kafka. Но ваше приложение прекрасно своей универсальностью🔥
1. [Асинхронный метод](https://github.com/Fr0stFree/CinemaUGC/blob/16edd751020215d9514fce2e5f64e5a152125fd0/event_collector/app/src/recorder.py#L37) + [синхронный](https://github.com/Fr0stFree/CinemaUGC/blob/16edd751020215d9514fce2e5f64e5a152125fd0/event_collector/app/src/recorder.py#L49) = проблемы с **event loop**
      Решения тут:
      - https://aiokafka.readthedocs.io/en/stable/#aiokafkaproducer
      - https://aio-pika.readthedocs.io/en/latest/
      - https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html
2. Я бы рекомендовал избегать [использования](https://github.com/Fr0stFree/CinemaUGC/blob/16edd751020215d9514fce2e5f64e5a152125fd0/event_processor/app/src/consumers/kafka_broker.py#L14) **enable_auto_commit**, который [к тому же и по умолчанию True](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html). C учетом того, что при чтении каждой записи из кафки происходит коммит смещения, во время перезагрузок сервиса батч будет сбрасываться, и данные будут теряться на совсем. Текущие данные, вероятно, не самая важная информация, но с какими-нибудь другими данными этот подход мог и не пройти. В этом случае как вариант - выполнять коммит только после вставки в ClickHouse.

**Comment by Fr0stFree** [comment]
1. [Переезд в Кафку](https://github.com/Fr0stFree/CinemaUGC/issues/10)
2. [Багфикс потери данных при автокоммите прочитанного из брокера сообщения](https://github.com/Fr0stFree/CinemaUGC/issues/11)

**Comment by BigDeepBlue** [comment]
LGTM
